services:
  wrxtest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wrx-test-runner
    volumes:
      - ./reports:/reports:rw
    environment:
      - TS_NAME=localtestrun
      - TEST_URLS=['https://example.org']
      - TEST_MIN-TRIPLES=1
    working_dir: /app
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
